name: sign_up_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # iOS style icons.
  cupertino_icons: ^1.0.2
  # State managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Comparing objects effectively to prevent rebuilds
  equatable: ^2.0.5
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization
  json_annotation: ^4.8.1
  # Firebase
  firebase_core: ^2.25.3
  # Firebase auth
  firebase_auth: ^4.17.3
  firebase_auth_platform_interface: ^7.1.3
  # Firebase storage
  firebase_storage: ^11.6.4
  # Firebase firestore DB
  cloud_firestore: ^4.15.3
  # Pin input widget
  pinput: ^3.0.1
  # Annotations for freezed
  freezed_annotation: ^2.4.1
  # Picking images from the image library, taking new pictures with the camera
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  # Code generator for data-classes
  freezed: ^2.4.7
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      # Icon font
    - family: SignUpTestApp
      fonts:
        - asset: assets/fonts/SignUpTestApp.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
